BaseService.mocks.ts added to extract mocks, but tests are broken
  ● Test suite failed to run

    test/service/BaseService.test.ts:154:28 - error TS2339: Property 'toHaveSameFields' does not exist on type 'Matchers<void, IOffer<ObjectId> | null> & SnapshotMatchers<void, IOffer<ObjectId> | null> & Inverse<JestMatchers<void, IOffer<...> | null>> & PromiseMatchers<...>'.

    154     expect(retrievedOffer).toHaveSameFields(createdOffer);