Getting the following error because I used ObjectId from bson
  ● Test suite failed to run

    src/impl/mongoose/dao/MongooseDaoFactory.ts:45:5 - error TS2322: Type 'OfferDao' is not assignable to type 'IOfferDao<ObjectId, IOffer<ObjectId>>'.
      Types of property 'loadSubOffers' are incompatible.
        Type '(parentOfferId: ObjectId) => Promise<IMongooseOffer[]>' is not assignable to type '(parentOfferId: ObjectId) => Promise<IOffer<ObjectId>[]>'.
          Types of parameters 'parentOfferId' and 'parentOfferId' are incompatible.
            Type 'ObjectId' is missing the following properties from type 'ObjectId': _bsontype, id, toHexString, toJSON, and 3 more.

    45     return this.offerDao;

 Known issue:
 https://github.com/Automattic/mongoose/issues/12711
 https://github.com/Automattic/mongoose/issues/12537